class AR {
  static const Map<String, String> arabic = {
    'login': 'تسجيل الدخول',
    'discover': 'اكتشف بيتك الجديد',
    'dicover_des':
        'Your New Home shoud be called Dream \n Land becuase it is really the stuff \n dreams are made of.',
    'register': 'تسجيل',
    'register_now': 'سجل الان',
    'First_name': 'الاسم الاول',
    'family_name': 'الاسم الثاني',
    'name': 'الاسم',
    'email': 'الايميل',
    'mobile': 'الموبايل',
    'password': 'الرقم السري',
    'c_password': 'تاكيد الرقم السري',
    'register_by': 'سجل بواسطه',
    'forget': 'هل نسيت كلمة السر?',
    'no_account': 'لا تمتلك اكونت?',
    'forget_pass': 'نسيت كلمة السر',
    'emailormobile': 'اكتب الايميل',
    'rest': 'ارسال',
    'new_pass': 'الرقم السري الجديد',
    'write_new_pass': 'اكتب رقمك السري الجديد',
    'c_write_new_pass': 'تاكيد الرقم السري',
    'about': 'عن العز جروب',
    'des': 'التفاصيل',
    'our_companies': 'شركتنا',
    'our_projects': 'مشاريعنا',
    'download': 'حمل الملف الخاص بتخطيط الارضيه',
    'buy': 'اشتري الان',
    'request': 'ارسال للشراء',
    'adress': 'العنوان',
    'job': 'وظيفيتك',
    'sales': 'اسمك البائع',
    'knows': 'كيف تعرفت علينا؟',
    'phase': 'اختر مرحله',
    'type': 'اختر النوع',
    'payment': 'اختر نظام الدفع',
    'cash': 'كاش',
    'installment': 'تقسيط',
    'period': 'مده التقسيط',
    'details': 'تفاصيل اكثر',
    '1year': 'سنه',
    '2year': 'سنتين',
    '3year': '3 سنين',
    'find_your_house': 'ابحث عن منزل لك',
    'search_result': 'نتائج البحث',
    'popular': 'المشهور',
    'favorite': 'المفضله',
    'favorite_result': 'نتائج',
    'lang': 'اللغات',
    'rate_app': 'قيم التطبيق',
    'our_contact': 'تواصلنا',
    'signout': 'تسجيل الخروج',
    'profile':'الملف الشخصي',
    'no_project': 'لا يوجد مشاريع'
  };
}
