class EN {
  static const Map<String, String> english = {
    'login': 'Login',
    'discover': 'Discover your new Home',
    'dicover_des':
        'Your New Home shoud be called Dream \n Land becuase it is really the stuff \n dreams are made of.',
    'register': 'Register',
    'register_now': 'Register Now',
    'first_name': 'First Name',
    'family_name': 'Family Name',
    'name': 'Name',
    'email': 'Email',
    'mobile': 'Mobile',
    'password': 'Password',
    'c_password': 'Confirm Password',
    'register_by': 'Register By',
    'forget': 'Forget your Password?',
    'no_account': 'Don`t have Account?',
    'forget_pass': 'Forget Passwrod',
    'emailormobile': 'Write your Email or Mobile Number',
    'rest': 'Send Reset',
    'new_pass': 'New Password',
    'write_new_pass': 'Write your New Password',
    'c_write_new_pass': 'Confirm your New Password',
    'about': 'About Elezz Group',
    'des': 'Description',
    'our_companies': 'Our Companies',
    'our_projects': 'Our Projects',
    'download': 'Download Attach PDF Floor Plan',
    'buy': 'Buy Now',
    'request': 'Request for Buy',
    'adress': 'Adress',
    'job': 'your Job',
    'sales': 'Name of your sales person',
    'knows': 'How did you Know us?',
    'phase': 'Chooes Phase',
    'type': 'Chooes Type',
    'payment': 'Chooes your payment system',
    'cash': 'Cash',
    'installment': 'installment',
    'period': 'A period of installment',
    'details': 'More details',
    '1year': '1 year',
    '2year': '2 year',
    '3year': '3 year',
    'find_your_house': 'Find your house',
    'search_result': 'result in your Search',
    'popular': 'Popular',
    'favorite': 'Favorite',
    'favorite_result': 'result in your Favorite',
    'lang': 'Language',
    'rate_app': 'Rate The App',
    'our_contact': 'Our Contact',
    'signout': 'Sign Out',
    'profile': 'My Profile',
    'no_project': 'No Projects'

  };
}
