class EN {
  static const Map<String, String> english = {
    'login': 'Login',
    'discover': 'Discover your new Home',
    'dicover_des':
        'Your New Home should be called Dream \n Land because it is really the stuff \n dreams are made of.',
    'register': 'Register',
    'register_now': 'Register Now',
    'first_name': 'First Name',
    'family_name': 'Family Name',
    'name': 'Name',
    'email': 'Email',
    'mobile': 'Mobile',
    'password': 'Password',
    'c_password': 'Confirm Password',
    'register_by': 'Register By',
    'forget': 'Forget your Password?',
    'no_account': 'Don`t have Account?',
    'forget_pass': 'Forget Passwrod',
    'emailormobile': 'Write your Email or Mobile Number',
    'rest': 'Send Reset',
    'send': 'Send',
    'new_pass': 'New Password',
    'write_new_pass': 'Write your New Password',
    'c_write_new_pass': 'Confirm your New Password',
    'about_us': 'About Elezz Group',
    'about': 'About',
    'des': 'Description',
    'our_companies': 'Our Companies',
    'our_projects': 'Our Projects',
    'download': 'Download Attach PDF Floor Plan',
    'buy': 'Buy Now',
    'request': 'Request for Buy',
    'address': 'Adress',
    'job': 'your Job',
    'sales': 'Name of your sales person',
    'knows': 'How did you Know us?',
    'phase': 'Chooes Phase',
    'type': 'Chooes Type',
    'payment': 'Chooes your payment system',
    'cash': 'Cash',
    'installment': 'installment',
    'period': 'A period of installment',
    'details': 'More details',
    '1year': '1 year',
    '2year': '2 year',
    '3year': '3 year',
    'find_your_house': 'Find your house',
    'search_result': 'result in your Search',
    'popular': 'Popular',
    'favorite': 'Favorite',
    'favorite_result': 'result in your Favorite',
    'lang': 'Language',
    'rate_app': 'Rate The App',
    'our_contact': 'Our Contact',
    'signout': 'Sign Out',
    'profile': 'My Profile',
    'no_project': 'No Projects',
    'select_lang': 'SELECT LANGUAGE',
    'currency': 'EGP',
    'map': 'View on Map',
    'year': '/year',
    'bedroom': 'Bedrooms',
    'bathroom': 'Bathrooms',
    'kitchen': 'Kitchens',
    'garage': 'Garages',
    'garden': 'Gardens',
    'company_des':
        'Is one of the leading real estate developers in Egypt and the Middle East, with a long history in this field and extensive experience. The Group has a track record of achievements over the last 30 years, developing large areas of residential and commercial projects, while sales of more than 1,000 real estate units.',
    'lajoie_des':
        'LA JOIE AIR RAS SIDR: A tourist project facade extends 360 meters on the sea depth of 700 meters, and the planned sales launch within the next 6 months. LA JOIE PYRAMIDS: Ahram Heights area Ahram Heights, an area of ​​12  thousand square meters and includes a service area of ​​2,500  square meters project will be a tower containing spaces for residential units wide. OCTOBER GARDENS: It is a project dedicated to him a plot of land estimated at about 270  acres project will be implemented on 50% of the land which is estimated at about 135  acres and will include all integrated residential services, is scheduled to begin drawing charts this year.',
    'nour_des':
        'Alnorhan consists of 17 buildings containing each building 24 housing units Investors Association area gardens in October with a total of 408 housing units.',
    'shokrak_des':
        'THE ACQUISITION OF THE COMPANY ”SHORAKA”A"MANSOREYA VIEW Development and real estate investment project owner mansouriet view full shares and projects',
    'mans':
        'Featuring Alcolmbund b Alfio picturesque nature where farms and fruit trees, palaces artists and spaces endless green spaces Alcolmbund is located on a hill 55 m where enables you to watch the charming nature to infinity villas stand Alon, ground floor and first and roof area vary between 250 m - 310m'
  };
}
